[menu]
executable = 'fuzzel'
args = ['--dmenu', '--prompt=ğŸªŸâ¯ ', '--width=100', '--minimal-lines']

[format]
window_format = "{app_name:{:<25.25}} â€œ{title:{:<48.48}...}â€ on {workspace_name:{:>7.7}}\u0000icon\u001f{app_icon}"
indent = '    '
